spring:
  profiles:
    active: dev
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-cn-x0r3dffls000jido.rwlb.rds.aliyuncs.com:3306/usercenter
    username: lixing
    password: Li200071
    # session 失效时间
  session:
    timeout: 86400
    store-type: redis
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  redis:
    database: 2
    host: r-bp15ybgggyheamxvebpd.redis.rds.aliyuncs.com
    port: 6379
    password: Li200071
server:
  port: 8080
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


#knife4j:
#  enable: true
#  openapi:
#    title: Knife4j官方文档
#    description: "user-center测试文档"
#    # aaa"
#    email: xiaoymin@foxmail.com
#    concat: steven
#    url: https://docs.xiaominfo.com
#    version: v4.0
#    license: Apache 2.0
#    license-url: https://stackoverflow.com/
#    terms-of-service-url: https://stackoverflow.com/
#    group:
#      test1:
#        group-name: 分组名称
#        api-rule: package
#        api-rule-resources:
#          - com.linchao.usercenter.controller